mpls: fix build with CONFIG_IPV6=m
With CONFIG_IPV6=m we would get:
ERROR: "mpls_ipv6_exit" [net/ipv6/ipv6.ko] undefined!
ERROR: "mpls_ipv6_init" [net/ipv6/ipv6.ko] undefined!

Because mpls.c was tried to be built as it's own separate mpls.ko.
This fixes it to be always built as part of ipv6 core.